#!/bin/sh

if [ -r $HOME/.config/dmenu/common.sh ]; then
  . $HOME/.config/dmenu/common.sh
fi

xrandr_tmp=$XDG_RUNTIME_DIR/xrandr.tmp
external_monitor=""

if [ -r "$xrandr_tmp" ]; then
  exit 0
fi

xrandr -q > $xrandr_tmp

trap "rm -f $xrandr_tmp" INT QUIT TERM EXIT

if   grep 'VGA1 connected' $xrandr_tmp; then
  external_monitor="VGA"
elif grep 'CRT1 connected' $xrandr_tmp; then
  external_monitor="VGA"
elif grep 'DVI1 connected' $xrandr_tmp; then
  external_monitor="DVI"
elif grep 'DFP1 connected' $xrandr_tmp; then
  external_monitor="HDMI"
elif grep 'HDMI1 connected' $xrandr_tmp; then
  external_monitor="HDMI"
fi

available_modes="left right above below clone only off"

if [ -n "$external_monitor" ]; then
  mode=$(for m in $available_modes; do echo $m; done | $DMENU_COMMAND -p "$external_monitor" ${1+"$@"})

  if [ -n "$mode" ]; then
  	xrandr-set ${external_monitor} ${mode}
  fi
else
  xrandr-set vga off
fi
