#!/bin/sh

# Dell Latitude D420
LCD="LVDS1"
VGA="VGA1"
DVI="DVI1"

# Dell Latitude D6430u
LCD="LVDS1"
VGA="VGA1"
HDMI="HDMI1"

# Thinkpad Edge 13
#LCD="LVDS"
#VGA="CRT1"
#HDMI="DFP1"
#DVI="DVI1"

usage() {
  echo "Usage: xrandr_set [output] [command]"
  echo ""
  echo "Outputs:"
  echo "  hdmi, vga"
  echo ""
  echo "Commands:"
  echo "  above, below, left, right, only, off"
  exit 1
}

toggle_audio() {
  if [ ! -r ~/.asoundrc ]; then
	cat > ~/.asoundrc <<EOF
pcm.hdmi_formatted {
  type plug slave.pcm "dmix:0,3"
}

pcm.hdmi_complete {
  type softvol
	slave.pcm hdmi_formatted
	control.name hdmi_volume
	control.card 0
}

pcm.!default hdmi_complete
EOF
  else
	rm -f ~/.asoundrc
  fi
}

if [ $# != 2 ]; then
  usage
fi

case $1 in
  dvi|DVI)	OUT=$DVI;;
  vga|VGA)	OUT=$VGA;;
  hdmi|HDMI)	OUT=$HDMI;;
  *)		usage;;
esac

case $2 in 
  above)  xrandr --output $LCD --primary --auto --output $OUT --auto --above $LCD	;;
  below)  xrandr --output $LCD --primary --auto --output $OUT --auto --below $LCD	;;
  left)   xrandr --output $LCD --primary --auto --output $OUT --auto --left-of $LCD   ;;
  right)  xrandr --output $LCD --primary --auto --output $OUT --auto --right-of $LCD  ;;
  only)   xrandr --output $LCD --off      --output $OUT --auto --primary	;;
  clone)  xrandr --output $LCD --same-as $OUT --auto --output $OUT --auto --primary   ;;
  off)  xrandr --output $LCD --primary --auto --output $OUT --off			;;
  audio)  toggle_audio;;
  *)	  usage;;
esac

rotate-wallpaper
transset -n i3bar 0.9

exit 0
